[package]
name = "daemos"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = { version = "0.31", features = ["serde"] }
eframe = { version = "0.31", default-features = false, features = [
    "default_fonts", # Embed the default egui fonts.
    "wgpu",          # Use the wgpu rendering backend. Alternative: "glow".
    "persistence",   # Enable restoring app state when restarting the app.
    "wayland",       # To support Linux (and CI)
    "x11",           # To support older Linux distributions (restores one of the default features)
] }
egui_extras = { version = "0.31.1", features = ["image"] }
catppuccin-egui = { version = "5.5.0", default-features = false, features = [
    "egui31",
] }
egui_dock = "0.16.0"
color-eyre = "0.6.4"
rfd = "0.15.3"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
walkdir = "2.5.0"
serde = { version = "1.0.219", features = ["derive"] }
rusqlite = { version = "0.35.0", features = ["bundled", "chrono"] }
config = { version = "0.15.11", default-features = false, features = ["toml"] }
uuid = { version = "1.16.0", features = ["v4", "fast-rng", "serde"] }
chrono = { version = "0.4.41", features = ["serde"] }
blake3 = { version = "1.8.2", features = ["serde"] }
crossbeam = "0.8.4"
rodio = { version = "0.20.1", features = ["symphonia-all"] }
symphonia = { version = "0.5.4", features = ["mp3", "flac", "wav"] }
sysinfo = { version = "0.35.1", features = ["serde"] }
notify-rust = "4.11.7"
image = { version = "0.25.6", features = ["png"] }
rand = "0.9.1"
thiserror = "2.0.12"
egui_plot = "0.32.1"
regex = "1.11.1"
